### PR TITLE
issue #3 correction

### PR DESCRIPTION
**Pull request by ricioli**
Correction of the following problem:
Cursor in tag will output class/id though search/cmd+p dialog has focus #3
To simulate: place cursor within an html tag and then use cmd+p and type a . this will output class="" into the previously selected html tag even though it's not in focus.

### CODE REVIEW

**Comment by revelt** [comment]
I just checked, it does work! Thank you sir! Will release soon.

**Comment by revelt** [comment]
0.7.0 published!!! This is awesome

**Review by bradfx — COMMENTED** [review]
Nice! A simple fix! I couldn't figure this one out! Thanks :D

**Comment by bradfx** [comment]
(@revelt Nevermind me I was trying to historically add you as a reviewer. Ignore that)

**Comment by revelt** [comment]
@bradleyflood  hehe no worries! this is a good-one, all the dot files used to trigger the classes.. glad it's fixed

**Pull request merged**
